version: '3.3'

services:
 php:
  container_name: php73
  depends_on:
   - db
  image: marcjauniau/php-image
  volumes:
   - ./php:/var/www/html/
  ports:
   - 8090:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: tutoseu
   MYSQL_DATABASE: MJ
   MYSQL_USER: Marc
   MYSQL_PASSWORD: 12345
  ports:
   - 3306:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: Marc
   PMA_PASSWORD: 12345
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80